### ISSUE TITLE
Book Shelf? Where?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#6]
We _need_ to organise our books once and for all. I'm thinking we can remove the downstairs (lounge) bookshelf keep that area tidy ...

@iteles if we end up not having any AirBnB guests while Em & Sam are away, should we _prioritise_ building the Closet Library? see: https://github.com/nelsonic/closet

**Comment by iteles** [comment]
We'll have from September 30th until October 5th (Sam comes back then) or 9th (that's when Em's back). 

How many hours do you think it will take _all in_?

**Comment by nelsonic** [comment]
_many_ hours... I don't even want to _think_ about that _right now_ ...
Lets talk next weekend. :+1:

**Comment by ghost** [comment]
Shouldn't this issue be in hq? Not sure how to move an issue on Github...

**Comment by iteles** [comment]
Ha, hi @markwilliamfirth 👋 

This was originally the backdrop for some of the videos @nelsonic had in mind, which is why it's here :blush: He built it so I think this can be closed! Right @nelsonic ?

<img width="1602" alt="dwyl HQ book shelf" src="https://cloud.githubusercontent.com/assets/4185328/18061777/ee78f504-6e1b-11e6-8ff0-c3bd035dfc14.png">

**Comment by ghost** [comment]
Hiiii @iteles ^^

**Comment by nelsonic** [comment]
closing issue. we're going to [investigate using Chroma Key](https://github.com/dwyl/video/issues/10) instead of a physical background. 😉
